### ISSUE TITLE
Exception when starting okvis_node

### ISSUE THREAD

**Issue by jasonwurzel** [ethz-asl/okvis_ros#12]
Hi, 
I just wanted to try okvis but I can't seem to make it run. When I start with the following command line

`roslaunch ./okvis_node.launch`

I get an exception in VioParametersReader::readConfigFile
most of the time the program terminates before the line 
`if (file["numKeyframes"].isInt()) {`
in the console I still see 
`I1109 09:09:38.382927 11489 VioParametersReader.cpp:85] Opened configuration file: /home/michael/catkin_ws/src/okvis_ros/okvis/config/config_fpga_p2_euroc.yaml`

and then 
`OpenCV Error: Bad argument (Invalid pointer to file storage) in cvGetFileNodeByName, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/persistence.cpp, line 740
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/persistence.cpp:740: error: (-5) Invalid pointer to file storage in function cvGetFileNodeByName`

But sometimes the program terminates even before that, so the configuration files isn't even opened and the log says
`terminate called after throwing an instance of 'okvis::VioParametersReader::Exception'
  what():  [Exception] /home/michael/catkin_ws/src/okvis_ros/okvis/okvis_common/src/VioParametersReader.cpp:84: readConfigFile() assert(file.isOpened()) failed: Could not open config file: /home/michael/catkin_ws/src/okvis_ros/okvis/config/config_fpga_p2_euroc.yaml`

so maybe it's some concurrency problem? 
the strange thing is, if I start without ros with the following line, all is well and running as it should:

`./okvis_app_synchronous ~/catkin_ws/src/okvis_ros/okvis/config/config_fpga_p2_euroc.yaml  ~/datasets/euroc/mav0/`

**Comment by weblucas** [comment]
roslaunch okvis_ros okvis_node.launch

**Comment by jasonwurzel** [comment]
that didn't help as it resulted in the same error

**Comment by weblucas** [comment]
I don't believe the problem is in the code because there are a lot people using. You should focus on the launch file first. Double check if the file /home/michael/catkin_ws/src/okvis_ros/okvis/config/config_fpga_p2_euroc.yaml exists and you have permission to open it

**Comment by jasonwurzel** [comment]
Hi @weblucas , 
thank you for your hints. Yes I have all the necessary permisions and the file exists. As I said, when starting okvis_app_synchronous with the same config file, everything works. 
As I'm no expert in linux/cmake/ros (but on a good trajectory to becoming one :-) ) I was a bit lost here. In the end I made it work by completely removing opencv from the system and reinstalling (from source). Maybe something was messed up: on the one hand I had opencv 2.x installed by apt-get, on the other hand I had opencv 3.x (from github). plus I put vision_opencv alongside okvis_ros in my catkin workspace.
So now I only installed the opencv master from github (+ contrib of course) and now it's working...

**Comment by weblucas** [comment]
Nice!
You can also use the https://github.com/ethz-asl/opencv2_catkin in future
developments.

Best

Lucas

**Comment by paulhaile** [comment]
I'm having the same issue as well. so to fix this I can download and install opencv2_catkin, and just add the build dependency to the okvis ros package.xml and rebuild?

**Comment by weblucas** [comment]
It is a safe solution. before you change something on the package.xml. just compile manually opencv2_catkin first. and check if solves your problem. catkin build opencv2_catkin and after catkin build okvis_ros

**Comment by paulhaile** [comment]
neat, seems to have solved my issue, thank you!

**Comment by paulhaile** [comment]
This seems to have caused issues with a seperate (non-ros package) that is dependent on opencv 3.2.0
In file included from /usr/local/include/opencv2/core.hpp:52:0,
                 from /usr/local/include/opencv2/highgui.hpp:46,
                 from /home/paulous/PIRVS_SDK_V0.2.0/apps/offline_slam.cpp:20:
/usr/local/include/opencv2/core/cvdef.h:328:15: error: redefinition of ‘union Cv32suf’
 typedef union Cv32suf
               ^
In file included from /home/paulous/workspace/catkin_ws/devel/include/opencv2/core/core.hpp:49:0,
                 from /home/paulous/workspace/catkin_ws/devel/include/opencv2/calib3d/calib3d.hpp:46,
                 from /home/paulous/PIRVS_SDK_V0.2.0/apps/offline_slam.cpp:18:
/home/paulous/workspace/catkin_ws/devel/include/opencv2/core/types_c.h:198:15: error: previous definition of ‘union Cv32suf’
 typedef union Cv32suf

Sorry I'm not too good with this stuff and have been debugging for a while now, any help is appreciated

**Comment by paulhaile** [comment]
fixed. I believe I just had too many instances of opencv not linked properly. Deleted all instances of opencv and rebuilt using version 3. also rebuilt ros against version 3 so everything is using the same version of opencv
