### ISSUE TITLE
Skipping propagation as only one IMU measurement has been given to frontend. Normal when starting up.

### ISSUE THREAD

**Issue by herogan2017** [ethz-asl/okvis_ros#21]
W0725 09:30:52.175683 27943 Frontend.cpp:282] - Skipping propagation as only one IMU measurement has been given to frontend. Normal when starting up.

when I run MH_01_easy/mav0/ dateset, I met above problem. who can tell me the result?
thanks a lot.

**Comment by herogan2017** [comment]
Already fixed!

**Comment by SiyuanHuang95** [comment]
Hi, Could you give one quick hint about how to solve that problem? I also run into that problem when I used my own dataset. :)

**Comment by weiningwei** [comment]
Hi, I also run into this problem when I used the euroc dataset. Could you tell me about how to solve this problem?

**Comment by hxj806** [comment]
Hi, I also meet this problem when I used the euroc dataset. Could you tell me about how to solve this problem?

**Comment by KimiWu-0556** [comment]
> Already fixed!
Hi, I also meet this problem when I used the euroc dataset. Could you tell me about how to solve this problem?
