### ISSUE TITLE
Basic configuration files for live SLAM

### ISSUE THREAD

**Issue by mhkabir** [ethz-asl/okvis_ros#4]
It'd be great if some example config files could be added to the repo, especially for the Euroc datasets. The README refers to the files, but they don't exist in the `config` folder.

Thanks!

**Comment by aforster** [comment]
Something like this?
https://github.com/ethz-asl/okvis/blob/b3edf8705ecdd8462c630017d83766e4b005c998/config/config_fpga_p2_euroc.yaml
It's in the other repo :)

**Comment by mhkabir** [comment]
Ah, I missed that. Apologies. I didn't realise that I hadn't checked the actual library repo (as opposed to the ROS wrapper) 

Thanks!

**Comment by aforster** [comment]
You're welcome.
