### ISSUE TITLE
running okvis with monocular camera?

### ISSUE THREAD

**Issue by ank700** [ethz-asl/okvis_ros#5]
I installed okvis pkg on ubuntu (ROS indigo) after reading about it at the following page:
https://plus.google.com/102378419534121891617
It is mentioned that okvis has also been tested with mono camera. How do I test okvis with a mono cam on a dataset or with a real camera? 
Also, I have a completely different hardware setup - UI mono cam and Crius (mpu-6050 imu). Is it possible to use okvis with only the above mentioned things? 
Can you give me some suggestions on how to do so?

Thanks a lot!

**Comment by aforster** [comment]
Have you tried deleting the second camera entry in the config file? E.g. https://github.com/ethz-asl/okvis/blob/b3edf8705ecdd8462c630017d83766e4b005c998/config/config_fpga_p2_euroc.yaml#L14-L23

**Comment by ank700** [comment]
Hi @aforster , thanks for your reply. I was able to run the dataset with the changes as you said above, but is it right? Isn’t the T_SC matrix (in the config file) for the stereo camera containing rotational and translational parameters. Which calibration software or ros package did you use for the monocular camera?

I am now trying to edit the "config_DOC1357.yaml" file in order to run my hardware setup. Is it enough to just edit the config file or do I have to make some changes the source-code as well. Can you tell me about the changes, if any?

**Comment by sleutenegger** [comment]
The calibration procedure is described in the README. You can have any number of cameras, including just one that is listed in the config yaml file.
