### ISSUE TITLE
[Question] Frame delayed and dropped frames

### ISSUE THREAD

**Issue by andre-nguyen** [ethz-asl/okvis_ros#7]
I'm trying to debug my setup where I'm getting a lot of these messages when playing back some bag files:

```
W0329 23:44:20.806663  5986 Subscriber.cpp:124] Frame delayed at time 751.180006000
E0329 23:44:20.811384  6013 FrameSynchronizer.cpp:104] Dropping frame with id 22681
```

What exactly do these messages indicate? Bad time stamping of images? Too much latency between the time stamp of the images and the time when they are received? My cameras are hardware triggered by my IMU but I guess its possible that I messed up my time stamping logic...

If it helps, okvis seems to work inconsistently, sometimes it will run on my bag file for 30 seconds and then lose tracking and diverge, sometimes it diverges after only 5 seconds.

**Comment by aforster** [comment]
`Frame delayed` means that there is still another frame in the queue. Meaning that one is being processed in the `frameConsumerLoop()`, one is waiting for that to finish and you just pushed a new one into the queue. Ideally this queue is always empty. The loop should be finished by the time a new frame gets added.
`Dropping frame..` happens in the synchronizer. That class combines multiple frames into a `MultiFrame`. E.g. if you have a stereo setup it combines the right and left image. It will drop the multiframe if one of the images is not added in time (~3 frames if I remember correctly). 
Now for why that happens... My guess is your computer is falling behind on processing the frames. Maybe you set the framerate a bit too high? If you want you can also activate the timers maybe it will help you find the issue.
You could try using the snychronous node and check the performance of okvis there. This is a kind of optimal scenario as it goes through the rosbag one message at a time and always waits with adding a new frame until the old one has been processed.

**Comment by andre-nguyen** [comment]
@aforster Thanks for the tips, I had indeed set my cameras to 30 fps. I'll lower that and see how it goes.
